-- Gerado a partir do outerHTML completo do Codex de Kanto enviado pelo usuário.
-- 44 grupos, 131 Pokémon/slots e 524 registros possíveis de raridade.

insert into public.pokemon (id, name, sprite_url, region) values
  (1, 'Bulbasaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png', 'Kanto'),
  (2, 'Ivysaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png', 'Kanto'),
  (3, 'Venusaur', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', 'Kanto'),
  (4, 'Charmander', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', 'Kanto'),
  (5, 'Charmeleon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png', 'Kanto'),
  (6, 'Charizard', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png', 'Kanto'),
  (7, 'Squirtle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png', 'Kanto'),
  (8, 'Wartortle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png', 'Kanto'),
  (9, 'Blastoise', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png', 'Kanto'),
  (10, 'Caterpie', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png', 'Kanto'),
  (11, 'Metapod', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png', 'Kanto'),
  (12, 'Butterfree', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png', 'Kanto'),
  (13, 'Weedle', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png', 'Kanto'),
  (14, 'Kakuna', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png', 'Kanto'),
  (15, 'Beedrill', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png', 'Kanto'),
  (16, 'Pidgey', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png', 'Kanto'),
  (17, 'Pidgeotto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png', 'Kanto'),
  (18, 'Pidgeot', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png', 'Kanto'),
  (19, 'Rattata', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png', 'Kanto'),
  (20, 'Raticate', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png', 'Kanto'),
  (21, 'Spearow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png', 'Kanto'),
  (22, 'Fearow', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png', 'Kanto'),
  (23, 'Ekans', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png', 'Kanto'),
  (24, 'Arbok', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png', 'Kanto'),
  (25, 'Pikachu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png', 'Kanto'),
  (26, 'Raichu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png', 'Kanto'),
  (27, 'Sandshrew', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png', 'Kanto'),
  (28, 'Sandslash', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png', 'Kanto'),
  (29, 'Nidoran Female', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png', 'Kanto'),
  (30, 'Nidorina', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png', 'Kanto'),
  (31, 'Nidoqueen', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png', 'Kanto'),
  (32, 'Nidoran Male', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png', 'Kanto'),
  (33, 'Nidorino', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png', 'Kanto'),
  (34, 'Nidoking', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png', 'Kanto'),
  (35, 'Clefairy', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png', 'Kanto'),
  (36, 'Clefable', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png', 'Kanto'),
  (37, 'Vulpix', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png', 'Kanto'),
  (38, 'Ninetales', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png', 'Kanto'),
  (39, 'Jigglypuff', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png', 'Kanto'),
  (41, 'Zubat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png', 'Kanto'),
  (42, 'Golbat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png', 'Kanto'),
  (43, 'Oddish', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png', 'Kanto'),
  (44, 'Gloom', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png', 'Kanto'),
  (45, 'Vileplume', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png', 'Kanto'),
  (46, 'Paras', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png', 'Kanto'),
  (47, 'Parasect', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png', 'Kanto'),
  (48, 'Venonat', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png', 'Kanto'),
  (49, 'Venomoth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png', 'Kanto'),
  (50, 'Diglett', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png', 'Kanto'),
  (51, 'Dugtrio', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png', 'Kanto'),
  (52, 'Meowth', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png', 'Kanto'),
  (53, 'Persian', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png', 'Kanto'),
  (54, 'Psyduck', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png', 'Kanto'),
  (55, 'Golduck', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png', 'Kanto'),
  (56, 'Mankey', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png', 'Kanto'),
  (57, 'Primeape', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png', 'Kanto'),
  (58, 'Growlithe', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png', 'Kanto'),
  (59, 'Arcanine', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png', 'Kanto'),
  (60, 'Poliwag', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png', 'Kanto'),
  (61, 'Poliwhirl', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png', 'Kanto'),
  (62, 'Poliwrath', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png', 'Kanto'),
  (63, 'Abra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png', 'Kanto'),
  (64, 'Kadabra', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png', 'Kanto'),
  (65, 'Alakazam', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png', 'Kanto'),
  (66, 'Machop', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png', 'Kanto'),
  (67, 'Machoke', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png', 'Kanto'),
  (68, 'Machamp', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png', 'Kanto'),
  (69, 'Bellsprout', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png', 'Kanto'),
  (70, 'Weepinbell', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png', 'Kanto'),
  (71, 'Victreebel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png', 'Kanto'),
  (72, 'Tentacool', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png', 'Kanto'),
  (73, 'Tentacruel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png', 'Kanto'),
  (74, 'Geodude', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png', 'Kanto'),
  (75, 'Graveler', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png', 'Kanto'),
  (76, 'Golem', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png', 'Kanto'),
  (77, 'Ponyta', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png', 'Kanto'),
  (78, 'Rapidash', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png', 'Kanto'),
  (79, 'Slowpoke', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png', 'Kanto'),
  (80, 'Slowbro', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png', 'Kanto'),
  (81, 'Magnemite', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png', 'Kanto'),
  (82, 'Magneton', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png', 'Kanto'),
  (83, 'Farfetchd', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png', 'Kanto'),
  (84, 'Doduo', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png', 'Kanto'),
  (85, 'Dodrio', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png', 'Kanto'),
  (86, 'Seel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png', 'Kanto'),
  (87, 'Dewgong', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png', 'Kanto'),
  (88, 'Grimer', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png', 'Kanto'),
  (89, 'Muk', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png', 'Kanto'),
  (90, 'Shellder', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png', 'Kanto'),
  (91, 'Cloyster', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png', 'Kanto'),
  (92, 'Gastly', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png', 'Kanto'),
  (93, 'Haunter', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png', 'Kanto'),
  (94, 'Gengar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png', 'Kanto'),
  (95, 'Onix', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png', 'Kanto'),
  (96, 'Drowzee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png', 'Kanto'),
  (97, 'Hypno', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png', 'Kanto'),
  (98, 'Krabby', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png', 'Kanto'),
  (99, 'Kingler', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png', 'Kanto'),
  (100, 'Voltorb', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png', 'Kanto'),
  (101, 'Electrode', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png', 'Kanto'),
  (102, 'Exeggcute', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png', 'Kanto'),
  (103, 'Exeggutor', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png', 'Kanto'),
  (104, 'Cubone', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png', 'Kanto'),
  (105, 'Marowak', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png', 'Kanto'),
  (106, 'Hitmonlee', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png', 'Kanto'),
  (107, 'Hitmonchan', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png', 'Kanto'),
  (108, 'Lickitung', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png', 'Kanto'),
  (109, 'Koffing', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png', 'Kanto'),
  (110, 'Weezing', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png', 'Kanto'),
  (111, 'Rhyhorn', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png', 'Kanto'),
  (112, 'Rhydon', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png', 'Kanto'),
  (114, 'Tangela', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png', 'Kanto'),
  (120, 'Staryu', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png', 'Kanto'),
  (121, 'Starmie', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png', 'Kanto'),
  (123, 'Scyther', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png', 'Kanto'),
  (124, 'Jynx', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png', 'Kanto'),
  (125, 'Electabuzz', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png', 'Kanto'),
  (126, 'Magmar', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png', 'Kanto'),
  (127, 'Pinsir', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png', 'Kanto'),
  (128, 'Tauros', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png', 'Kanto'),
  (130, 'Gyarados', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png', 'Kanto'),
  (131, 'Lapras', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png', 'Kanto'),
  (140, 'Kabuto', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png', 'Kanto'),
  (141, 'Kabutops', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png', 'Kanto'),
  (142, 'Aerodactyl', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png', 'Kanto'),
  (143, 'Snorlax', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png', 'Kanto'),
  (147, 'Dratini', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png', 'Kanto'),
  (148, 'Dragonair', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png', 'Kanto'),
  (149, 'Dragonite', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png', 'Kanto'),
  (215, 'Sneasel', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/215.png', 'Kanto'),
  (261, 'Poochyena', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/261.png', 'Kanto')
on conflict (id) do update set name = excluded.name, sprite_url = excluded.sprite_url, region = excluded.region;

insert into public.codex_groups (id, region, attribute, short_attribute, display_order) values
  (1, 'Kanto', 'Velocidade', 'SPD', 1),
  (2, 'Kanto', 'Ataque', 'ATK', 2),
  (3, 'Kanto', 'Atq. Especial', 'SATK', 3),
  (4, 'Kanto', 'Defesa', 'DEF', 4),
  (5, 'Kanto', 'HP', 'HP', 5),
  (6, 'Kanto', 'Def. Especial', 'SDEF', 6),
  (7, 'Kanto', 'Velocidade', 'SPD', 7),
  (8, 'Kanto', 'Defesa', 'DEF', 8),
  (9, 'Kanto', 'Ataque', 'ATK', 9),
  (10, 'Kanto', 'Atq. Especial', 'SATK', 10),
  (11, 'Kanto', 'HP', 'HP', 11),
  (12, 'Kanto', 'HP', 'HP', 12),
  (13, 'Kanto', 'Ataque', 'ATK', 13),
  (14, 'Kanto', 'Def. Especial', 'SDEF', 14),
  (15, 'Kanto', 'Defesa', 'DEF', 15),
  (16, 'Kanto', 'HP', 'HP', 16),
  (17, 'Kanto', 'Ataque', 'ATK', 17),
  (18, 'Kanto', 'Defesa', 'DEF', 18),
  (19, 'Kanto', 'Ataque', 'ATK', 19),
  (20, 'Kanto', 'Def. Especial', 'SDEF', 20),
  (21, 'Kanto', 'Ataque', 'ATK', 21),
  (22, 'Kanto', 'Defesa', 'DEF', 22),
  (23, 'Kanto', 'HP', 'HP', 23),
  (24, 'Kanto', 'Defesa', 'DEF', 24),
  (25, 'Kanto', 'Def. Especial', 'SDEF', 25),
  (26, 'Kanto', 'Atq. Especial', 'SATK', 26),
  (27, 'Kanto', 'Def. Especial', 'SDEF', 27),
  (28, 'Kanto', 'HP', 'HP', 28),
  (29, 'Kanto', 'Atq. Especial', 'SATK', 29),
  (30, 'Kanto', 'Def. Especial', 'SDEF', 30),
  (31, 'Kanto', 'Velocidade', 'SPD', 31),
  (32, 'Kanto', 'Velocidade', 'SPD', 32),
  (33, 'Kanto', 'Velocidade', 'SPD', 33),
  (35, 'Kanto', 'Atq. Especial', 'SATK', 34),
  (36, 'Kanto', 'Defesa', 'DEF', 35),
  (37, 'Kanto', 'Ataque', 'ATK', 36),
  (39, 'Kanto', 'Atq. Especial', 'SATK', 37),
  (40, 'Kanto', 'Velocidade', 'SPD', 38),
  (41, 'Kanto', 'Def. Especial', 'SDEF', 39),
  (42, 'Kanto', 'HP', 'HP', 40),
  (43, 'Kanto', 'Defesa', 'DEF', 41),
  (44, 'Kanto', 'Atq. Especial', 'SATK', 42),
  (45, 'Kanto', 'Def. Especial', 'SDEF', 43),
  (48, 'Kanto', 'Def. Especial', 'SDEF', 44)
on conflict (id) do update set region = excluded.region, attribute = excluded.attribute, short_attribute = excluded.short_attribute, display_order = excluded.display_order;

insert into public.codex_group_members (group_id, pokemon_id, position) values
  (1, 63, 1),
  (1, 93, 2),
  (1, 17, 3),
  (2, 142, 1),
  (2, 107, 2),
  (2, 16, 3),
  (3, 65, 1),
  (3, 106, 2),
  (3, 25, 3),
  (4, 24, 1),
  (4, 97, 2),
  (4, 112, 3),
  (5, 59, 1),
  (5, 2, 2),
  (5, 127, 3),
  (6, 15, 1),
  (6, 39, 2),
  (6, 60, 3),
  (7, 69, 1),
  (7, 124, 2),
  (7, 61, 3),
  (8, 9, 1),
  (8, 140, 2),
  (8, 62, 3),
  (9, 1, 1),
  (9, 141, 2),
  (9, 77, 3),
  (10, 12, 1),
  (10, 64, 2),
  (10, 57, 3),
  (11, 10, 1),
  (11, 14, 2),
  (11, 54, 3),
  (12, 88, 1),
  (12, 89, 2),
  (12, 108, 3),
  (13, 4, 1),
  (13, 99, 2),
  (13, 78, 3),
  (14, 5, 1),
  (14, 109, 2),
  (14, 20, 3),
  (15, 36, 1),
  (15, 98, 2),
  (15, 19, 3),
  (16, 35, 1),
  (16, 131, 2),
  (16, 111, 3),
  (17, 32, 1),
  (17, 56, 2),
  (17, 71, 3),
  (18, 91, 1),
  (18, 68, 2),
  (18, 28, 3),
  (19, 104, 1),
  (19, 67, 2),
  (19, 123, 3),
  (20, 87, 1),
  (20, 66, 2),
  (20, 86, 3),
  (21, 85, 1),
  (21, 147, 2),
  (21, 149, 3),
  (22, 261, 1),
  (22, 27, 2),
  (22, 75, 3),
  (23, 84, 1),
  (23, 126, 2),
  (23, 79, 3),
  (24, 80, 1),
  (24, 90, 2),
  (24, 102, 3),
  (25, 148, 1),
  (25, 82, 2),
  (25, 143, 3),
  (26, 114, 1),
  (26, 6, 2),
  (26, 81, 3),
  (27, 72, 1),
  (27, 73, 2),
  (27, 21, 3),
  (28, 96, 1),
  (28, 105, 2),
  (28, 7, 3),
  (29, 51, 1),
  (29, 52, 2),
  (29, 121, 3),
  (30, 23, 1),
  (30, 11, 2),
  (30, 120, 3),
  (31, 26, 1),
  (31, 41, 2),
  (31, 50, 3),
  (32, 53, 1),
  (32, 101, 2),
  (32, 125, 3),
  (33, 128, 1),
  (33, 215, 2),
  (35, 103, 1),
  (35, 34, 2),
  (35, 49, 3),
  (36, 83, 1),
  (36, 31, 2),
  (36, 48, 3),
  (37, 22, 1),
  (37, 29, 2),
  (37, 3, 3),
  (39, 92, 1),
  (39, 30, 2),
  (39, 45, 3),
  (40, 94, 1),
  (40, 33, 2),
  (40, 100, 3),
  (41, 74, 1),
  (41, 38, 2),
  (41, 37, 3),
  (42, 44, 1),
  (42, 43, 2),
  (42, 8, 3),
  (43, 42, 1),
  (43, 95, 2),
  (43, 13, 3),
  (44, 55, 1),
  (44, 46, 2),
  (44, 70, 3),
  (45, 76, 1),
  (45, 47, 2),
  (45, 110, 3),
  (48, 58, 1),
  (48, 130, 2),
  (48, 18, 3)
on conflict (group_id, pokemon_id) do update set position = excluded.position;
